[tool.pytest]
minversion = "9.0"
addopts = [
    "--cov=src",
    "--cov-report=term-missing",
    "--exitfirst",
    "--last-failed",
    "-rA",
    "--showlocals",
    "--verbosity=0"
    ]
console_output_style = "count"
filterwarnings = [
    "error",
    "ignore::DeprecationWarning"
    ]
log_cli = false
log_file = "logs/pytest-logs.txt"
markers = [
    "smoke"
    ]
required_plugins = [
    "pytest-cov",
    "pytest-html",
    "pytest-mock",
    "pytest-rerunfailures",
    "pytest-sugar",
    "pytest-timeout",
    "pytest-xdist"
    ]
strict = true
testpaths = [
    "tests/unit"
    ]
